name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v[0-9].[0-9]+.[0-9]+.[0-9]+']

env:
  SOLUTION_NAME: OopsAllLalafells
  INTERNAL_NAME: OopsAllLalafells
  RELEASE_DIR: bin\Release\OopsAllLalafells
  PERSONAL_PLUGIN_REPO: buengese/DalamudPlugins

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"   
      - name: Build
        run: |
          dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
          dotnet build --configuration Release
      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal
      - uses: actions/upload-artifact@v2
        with:
          name: PluginRepoZip
          path: ${{ env.RELEASE_DIR }}
          if-no-files-found: error

  deploy:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.PERSONAL_PLUGIN_REPO }}
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v2
        with:
          name: PluginRepoZip
          path: plugins/${{ env.INTERNAL_NAME }}
      - uses: EndBug/add-and-commit@v7
        with:
          add: --all
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          branch: master
          message: Update ${{ env.INTERNAL_NAME }}
